spring:
  application:
    name: yxdsso
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yxdsso?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      max-active: 1000
      initial-size: 10
      max-wait: 1000
      min-idle: 10
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 0
server:
  port: 8081
  servlet:
    context-path: /sso
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: edu.nf.yxdsso.entity